# Generated by Django 5.2.3 on 2025-07-03 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_remove_subscription_is_subscribed"),
        ("users", "0005_payment_link_to_payment_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="course_paid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date_paid",
            field=models.DateField(blank=True, null=True, verbose_name="Дата платежа"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="lesson_paid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
