# Generated by Django 5.2.3 on 2025-06-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_lesson_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
