# Generated by Django 5.2.3 on 2025-06-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="Is_subscribed",
            new_name="is_subscribed",
        ),
    ]
