# Generated by Django 5.2.3 on 2025-06-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_rename_is_subscribed_subscription_is_subscribed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_subscribed",
        ),
    ]
